name: CI Test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Setup node 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: pnpm
        
    - name: Install deps
      run: pnpm install
    
    - name: Test Build
      run: pnpm run build:test

    - name: Install Electron
      run: node node_modules/electron/install.js

    - name: Test in Electron
      run: pnpm run test:ci
      timeout-minutes: 5